namespace $ {

	export const $bog_gamestudio_case_source = [
		'$bog_gamestudio_case $bog_gamestudio_sample_map',
		'\tatlas <= Atlas',
		'\tmap \\',
		'\t\t\\######',
		'\t\t\\#....#',
		'\t\t\\#..#.#',
		'\t\t\\#....#',
		'\t\t\\######',
		'\tpalette *',
		'\t\t# \\wall',
		'\t\t. \\floor',
		'\tkids /',
		'\t\t<= Hero $bog_gamestudio_sample_hero',
		'\t\t\tname \\Герой',
		'\t\t\tatlas <= Atlas',
		'\t\t\tinput <= input',
		'\t\t\tframe \\hero',
		'\t\t\tpos / 3.25 0 0',
		'\t\t\tspeed 3',
		'\t\t<= Coin $bog_gamengine_sprite',
		'\t\t\tname \\Монета',
		'\t\t\tatlas <= Atlas',
		'\t\t\tframe \\coin',
		'\t\t\tpos / 2 0 0',
		'\t\t\ttint / 1 0.5 0.25 1',
		'\t\t<= Wall $bog_gamengine_sprite',
		'\t\t\tname \\Стена',
		'\t\t\tatlas <= Atlas',
		'\t\t\tframe \\wall',
		'\t\t\tpos / 0 0 0',
		'\t\t\tscale / 2 2 1',
		'\t\t<= Sprite_1 $bog_gamengine_sprite',
		'\t\t\tname \\Ключ',
		'\t\t\tatlas <= Atlas',
		'\t\t\tframe \\coin',
		'\t\t\tpos / 10.5 -1.5 0',
		'\tAtlas $bog_gamengine_atlas',
		'\t\turis /',
		'\t\t\t\\bog/gamengine/demo/atlas/hero.png',
		'\t\t\t\\bog/gamengine/demo/atlas/coin.png',
		'\t\t\t\\bog/gamengine/demo/atlas/wall.png',
		'\t\t\t\\bog/gamengine/demo/atlas/floor.png',
		'\t\tsize 64',
	].join( '\n' ) + '\n'

}
